---
#     namespace: "games"
#     server_stats: "forge"

- name: Debug vars
  debug:
    msg: |
      Deploying {{ instance }} {{ version }} in {{ namespace }}
        itzg image tag: {{ itzg_tag }}
        Listening on: {{ network_address }}:{{ svc_port }}
        Min CPU: {{ min_cpu }} Max CPU: {{ max_cpu }}
        Min RAM: {{ min_ram }} Max RAM: {{ max_ram }}
        Writeable Directories:
          /data {{ etc_size }}
           |- backups {{ backup_size }}
           |- world {{ world_size }}
           |- save {{ save_size }}
           |- mods {{ mods_size }}

- name: Create Namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          pod-security.kubernetes.io/warn: restricted
          pod-security.kubernetes.io/warn-version: latest
        
- name: Create Persistent Volume Claims
  failed_when: false # ignore failure if PVC already exists
  with_items:
    - name: "{{ instance }}"
      size: "{{ etc_size }}"
    - name: "{{ instance }}-world"
      size: "{{ world_size }}"
    - name: "{{ instance }}-save"
      size: "{{ save_size }}"
    - name: "{{ instance }}-mods-{{ version }}"
      size: "{{ mods_size }}"
    - name: "{{ instance }}-backups"
      size: "{{ backup_size }}"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ namespace }}"
        labels:
          game: minecraft
          app: "{{ instance }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ item.size }}"

- name: Create RCON Secret
  no_log: true
  register: rconSecret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ instance }}-rcon-{{ version }}"
        namespace: "{{ namespace }}"
        labels:
          game: minecraft
          app: "{{ instance }}"
      type: Opaque
      data:
        password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') | b64encode }}"

- name: Update API KEY Secret
  no_log: true
  register: apiKeySecret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "cf-api-key"
        namespace: "{{ namespace }}"
        labels:
          game: minecraft
      type: Opaque
      data:
        key: "{{ cf_api_key | b64encode }}"

- name: Create Environment ConfigMap
  register: envConfigMap_cm
  kubernetes.core.k8s:
    definition: "{{ envConfigMap | to_yaml }}"

- name: Create ops.json ConfigMap
  register: ops_json_cm
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ instance }}-ops-{{ version }}"
        namespace: "{{ namespace }}"
        labels:
          game: minecraft
          app: "{{ instance }}"
      data:
        ops.json: "{{ ops_json | to_json(indent=2,sort_keys=true) }}"

# - name: Create Minecraft Policy
#   kubernetes.core.k8s:
#     definition:
#       apiVersion: projectcalico.org/v3
#       kind: NetworkPolicy
#       metadata:
#         name: "default-minecraft-allow"
#         namespace: "{{ namespace }}"
#         labels:
#           game: minecraft
#       spec:
#         selector: game == 'minecraft'
#         ingress:
#           - action: Allow
#             protocol: TCP
#             destination:
#               ports:
#                 - 25565
#           - action: Allow
#             protocol: TCP
#             destination:
#               ports:
#                 - 9150
#             source:
#               namespaceSelector: app.kubernetes.io/name == 'prometheus'

- name: Create Deployment
  register: deployment
  kubernetes.core.k8s:
    apply: yes
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ instance }}"
        namespace: "{{ namespace }}"
        labels:
          game: minecraft
          app: "{{ instance }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ instance }}"
            game: minecraft
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        template:
          metadata:
            labels:
              app: "{{ instance }}"
              game: minecraft
          spec:
            nodeSelector:
              kubernetes.io/role: gamer
            initContainers:
              - name: copy-ops
                image: "itzg/minecraft-server:{{ itzg_tag }}"
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                command:
                  - /bin/bash
                  - -c
                args:
                  - cat /tmp/ops.json; cp -f /tmp/ops.json /data/ops.json;
                volumeMounts:
                  - name: "{{ instance }}"
                    mountPath: /data
                  - name: "{{ instance }}-ops"
                    mountPath: /tmp
              - name: check-update
                image: "itzg/minecraft-server:{{ itzg_tag }}"
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                command:
                  - /bin/bash
                  - -c
                args:
                  - |
                    old_version_zip=$(find /data -maxdepth 1 -type f -name "*.zip" | grep -v {{ version }});
                    if [ -n "$old_version_zip" ]; then
                      echo "Removing old server pack zip";
                      rm -rf $old_version_zip;
                      echo "Moving old server start script";
                      mv -f /data/start.sh /data/start.sh.bak;
                    fi
                volumeMounts:
                  - name: "{{ instance }}"
                    mountPath: /data
            containers:
              - name: "{{ instance }}"
                image: "itzg/minecraft-server:{{ itzg_tag }}"
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                imagePullPolicy: Always
                ports:
                  - containerPort: 25565
                    name: minecraft
                    protocol: TCP
                volumeMounts:
                  - name: "{{ instance }}"
                    mountPath: /data
                  - name: "{{ instance }}-world"
                    mountPath: /data/world
                  - name: "{{ instance }}-save"
                    mountPath: /data/save
                  - name: "{{ instance }}-mods"
                    mountPath: /data/mods
                  - name: "{{ instance }}-backups"
                    mountPath: /data/backups"
                  - name: "tmp"
                    mountPath: /tmp
                resources:
                  requests:
                    memory: "{{ envConfigMap.data.MAX_MEMORY }}"
                    cpu: "{{ (min_cpu | float * 1.5 ) | round(0, 'ceil') | int }}000m"
                  limits:
                    memory: "{{ ((envConfigMap.data.MAX_MEMORY | split('G') | first | float) * 1.5) | round(0, 'ceil') | int }}G"
                    cpu: "{{ (max_cpu | float * 1.5 ) | round(0, 'ceil') | int }}000m"
                envFrom:
                  - configMapRef:
                      name: "{{ instance }}-env-{{ version }}"
                env:
                  - name: RCON_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: "{{ instance }}-rcon-{{ version }}"
                        key: password
                  - name: CF_API_KEY
                    valueFrom:
                      secretKeyRef:
                        name: cf-api-key
                        key: key
                  - name: PROXY
                    value: "{{ network.proxy }}"
                dnsConfig:
                  nameservers:
                  - 1.1.1.1
                  - 1.0.0.1
                livenessProbe:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 30
                  periodSeconds: 15
                  failureThreshold: 3
                  successThreshold: 1
                  timeoutSeconds: 1
                readinessProbe:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 30
                  periodSeconds: 15
                  failureThreshold: 3
                  successThreshold: 1
                  timeoutSeconds: 1
                startupProbe:
                  exec:
                    command:
                      - mc-health
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  failureThreshold: 600
                  successThreshold: 1
                  timeoutSeconds: 1
              - name: minecraft-exporter
                image: "ghcr.io/dirien/minecraft-exporter:0.19.0"
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                ports:
                  - containerPort: 9150
                    name: metrics
                    protocol: TCP
                resources:
                  requests:
                    memory: "16M"
                    cpu: "100m"
                  limits:
                    memory: "128M"
                    cpu: "500m"
                env:
                  - name: MC_WORLD
                    value: /data/world
                  - name: MC_MOD_SERVER_STATS
                    value: "{{ server_stats }}"
                  - name: MC_RCON_ADDRESS
                    value: ":25575"
                  - name: MC_RCON_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: "{{ instance }}-rcon-{{ version }}"
                        key: password
                volumeMounts:
                  - name: "{{ instance }}-world"
                    mountPath: /data/world
                    readOnly: true
                livenessProbe:
                  httpGet:
                    path: /
                    port: 9150
                  initialDelaySeconds: 30
                  timeoutSeconds: 10
                readinessProbe:
                  httpGet:
                    path: /
                    port: 9150
                  initialDelaySeconds: 30
                  timeoutSeconds: 10
            volumes:
              - name: "{{ instance }}"
                persistentVolumeClaim:
                  claimName: "{{ instance }}"
              - name: "{{ instance }}-mods"
                persistentVolumeClaim:
                  claimName: "{{ instance }}-mods-{{ version }}"
              - name: "{{ instance }}-world"
                persistentVolumeClaim:
                  claimName: "{{ instance }}-world"
              - name: "{{ instance }}-save"
                persistentVolumeClaim:
                  claimName: "{{ instance }}-save"
              - name: "{{ instance }}-backup"
                persistentVolumeClaim:
                  claimName: "{{ instance }}-backup"
              - name: "{{ instance }}-ops"
                configMap:
                  name: "{{ instance }}-ops-{{ version }}"
              - name: "tmp"
                emptyDir: {}

- name: Create Services
  kubernetes.core.k8s:
    apply: yes
    template: service.yml.j2

- name: Restart Deployment
  shell: kubectl -n {{ namespace }} rollout restart deploy {{ instance }}

- name: Wait for Deployment to be Ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "{{ instance }}"
  register: deployment

- name: Debug
  debug:
    var: deployment