# This is a basic workflow to help you get started with Actions

name: Deploy Modpack

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tags to run'
        required: true
        default: 'server'
        type: string
      modpack:
        description: 'Enter modpack to run'
        required: true
        type: choice
        options:
          - gtnh
          - prominence-ii
          - skyfactory-5
          - atm-10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ['self-hosted', 'ansible']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      
      - name: Setup vault token
        run: |
          echo "${{ secrets.VAULT_DECRYPT_TOKEN }}" > /tmp/vault_pass

      #TODO: use the same ip for all minecraft servers
      - name: Determine IP address
        id: ip
        run: |
          extra_vars=""
          if [ "${{ github.event.inputs.modpack }}" == "gtnh" ]; then
            extra_vars="--extra-vars svc_port=25565"
          elif [ "${{ github.event.inputs.modpack }}" == "prominence-ii" ]; then
            extra_vars="--extra-vars svc_port=25566"
          elif [ "${{ github.event.inputs.modpack }}" == "atm-10" ]; then
            extra_vars="--extra-vars svc_port=25567"
          elif [ "${{ github.event.inputs.modpack }}" == "skyfactory-5" ]; then
            extra_vars="--extra-vars svc_port=25568"
          fi
          echo "::set-output name=extra_vars::${extra_vars}"

      # Runs a single command using the runners shell
      - name: Deploy minecraft server
        run: |
          ansible-playbook -v -i inventory/hosts.ini ${{ github.event.inputs.modpack }}.yml --vault-password-file /tmp/vault_pass --tags "${{ github.event.inputs.tags }}" --extra-vars "network_address=3.100" ${{ steps.ip.outputs.extra_vars }}"

      - name: Remove vault token
        run: |
          rm /tmp/vault_pass
        
        
